Add AI processing, store, and search commands to DA [WEB-2934]
art-institute-of-chicago/data-aggregator pull request #87
Opened 2024-11-26 21:54 UTC by web-dev-trev

2024-12-02 19:32 UTC, zachgarwood commented on app/Console/Commands/BaseCommand.php
> +        return $this->info(" --------------- \n|               |\n|               |\n|               |\n|               |\n|               |\n|               |\n|        A I C  |\n --------------- ")
💖

2024-12-02 20:01 UTC, zachgarwood requested changes
Really interesting!

2024-12-02 20:01 UTC, zachgarwood commented on app/Http/Middleware/AIServiceStatus.php
> +        if (!config('azure.status', true)) {
I don't think we want to default to `true` if the `azure.status` is not set.

2024-12-02 20:01 UTC, zachgarwood commented on app/Services/DescriptionService.php
> +            EOT;
TIL that the heredoc ending identifier no longer has to start in the first column:
https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

2024-12-02 20:01 UTC, zachgarwood commented on app/Services/EmbeddingService.php
> +                if (!empty($caption['text']) && ($caption['confidence'] ?? 0) > 0.7) {
I think the `0.7` should be made into a constant like `CONFIDENCE_THRESHOLD_TEXT` or something similar, with a comment explaining the reasoning.

2024-12-02 20:01 UTC, zachgarwood commented on app/Services/EmbeddingService.php
> +                if (!empty($tag['name']) && ($tag['confidence'] ?? 0) > 0.9) {
I think this `09` should be a constant, as well.

2024-12-02 20:01 UTC, zachgarwood commented on app/Services/VectorSearchService.php
Very cool stuff!

2024-12-02 20:01 UTC, zachgarwood commented on config/azure.php
> +        'version' => env(key: 'AZURE_EMBEDDING_API_VERSION')
Should we set a default for these endpoint `version`s?

2024-12-19 18:34 UTC, nikhiltri approved these changes
Good work! ⭐ 

I think this is ready to go. I left a few question in here. Let's review and deploy together during our 1:1.

2024-12-19 18:34 UTC, nikhiltri commented on app/Console/Commands/AI/AnalyzeImage.php
> +            'https://www.artic.edu/iiif/2/%s/full/full/0/default.jpg',
Consider using `config('aic.config_documentation.iiif_url')` here.

2024-12-19 18:34 UTC, nikhiltri commented on database/migrations/2024_12_02_142650_create_vector_db_and_tables.php
> +        DB::statement('CREATE EXTENSION IF NOT EXISTS vector');
Dupe from previous migration, delete this line.

2024-12-19 20:26 UTC, merged